on:
  release:
    types:
      - created

name: documentation refresh
jobs:
  build:
    name: Renew documentation
    runs-on: ubuntu-latest
    steps:
    - name: Pull new module version
      uses: andrewslotin/go-proxy-pull-action@master
      with:
        goproxy: https://gocenter.io
