name: Update Go Proxy

on:
  release:
    types: [created]

jobs:
  proxy-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Trigger Go proxy pull
        uses: andrewslotin/go-proxy-pull-action@master
